name: OpenBMC CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.10-slim
      options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y qemu-system-arm
        pip install pytest pytest-html selenium

    - name: Run functional tests
      run: |
        cd tests/functional
        pytest test_power_control.py --html=report.html

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: power-control-test-report
        path: tests/functional/report.html